In [1]:
import pandas as pd
import numpy as np


In [2]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv("cars.csv")
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [41]:
# Q2. Records count

df.shape

(2160, 12)

In [5]:
# Q3. Laptop brands

df.Brand.nunique()

27

In [40]:
# Q4. Missing values

df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             0
Touch              0
Final Price        0
dtype: int64

In [39]:
# Q5. Maximum final price

df_dell = df[df["Brand"] == "Dell"]
df_dell["Final Price"].max()

3936.0

In [ ]:
# Median value of Screen

In [11]:
df["Screen"]

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [13]:
df["Screen"].describe()

count    2156.000000
mean       15.168112
std         1.203329
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: Screen, dtype: float64

In [14]:
df.Screen.median()

15.6

In [97]:
df.groupby("Screen").describe()

RAM                                                      Storage  \
         count       mean        std   min   25%   50%   75%    max   count   
Screen                                                                        
10.10      1.0   4.000000        NaN   4.0   4.0   4.0   4.0    4.0     1.0   
10.50      7.0   8.000000   0.000000   8.0   8.0   8.0   8.0    8.0     7.0   
10.95      1.0   8.000000        NaN   8.0   8.0   8.0   8.0    8.0     1.0   
11.60     16.0   4.000000   0.000000   4.0   4.0   4.0   4.0    4.0    16.0   
12.00      4.0   8.000000   0.000000   8.0   8.0   8.0   8.0    8.0     4.0   
12.30     13.0  14.153846   6.656402   8.0   8.0  16.0  16.0   32.0    13.0   
12.40      6.0   6.666667   2.065591   4.0   5.0   8.0   8.0    8.0     6.0   
12.50      1.0   8.000000        NaN   8.0   8.0   8.0   8.0    8.0     1.0   
13.00     27.0  11.555556   4.050957   8.0   8.0   8.0  16.0   16.0    27.0   
13.30    131.0  11.145038   4.492938   4.0   8.0   8.0  16.0   32.0   131.0   
13.40     19.0  20.631579   8.139141   8.0  16.0  16.0  32.0   32.0    19.0   
13.50     19.0  11.368421   4.058058   8.0   8.0   8.0  16.0   16.0    19.0   
13.60     11.0   9.454545   3.236159   8.0   8.0   8.0   8.0   16.0    11.0   
13.90      2.0  12.000000   5.656854   8.0  10.0  12.0  14.0   16.0     2.0   
14.00    392.0  13.071429   6.191736   4.0   8.0  16.0  16.0   40.0   392.0   
14.10     11.0   6.000000   1.788854   4.0   4.0   6.0   8.0    8.0    11.0   
14.20     14.0  22.857143   8.216841  16.0  16.0  16.0  32.0   32.0    14.0   
14.40      6.0  21.333333   8.262364  16.0  16.0  16.0  28.0   32.0     6.0   
14.50      3.0  16.000000   0.000000  16.0  16.0  16.0  16.0   16.0     3.0   
15.00     21.0  14.095238   7.112698   8.0   8.0  16.0  16.0   32.0    21.0   
15.30      8.0   8.000000   0.000000   8.0   8.0   8.0   8.0    8.0     8.0   
15.40      5.0  16.000000   0.000000  16.0  16.0  16.0  16.0   16.0     5.0   
15.60   1009.0  13.375619   7.341624   4.0   8.0  12.0  16.0   64.0  1009.0   
16.00    174.0  24.436782  11.455570   8.0  16.0  16.0  32.0   64.0   174.0   
16.10     48.0  15.833333   6.494952   8.0  16.0  16.0  16.0   32.0    48.0   
16.20     10.0  22.400000   8.262364  16.0  16.0  16.0  32.0   32.0    10.0   
17.00     33.0  32.000000  13.856406  16.0  32.0  32.0  32.0   64.0    33.0   
17.30    161.0  26.857143  15.820421   4.0  16.0  32.0  32.0  128.0   161.0   
18.00      3.0  32.000000   0.000000  32.0  32.0  32.0  32.0   32.0     3.0   

                     ...                 Final Price               \
               mean  ...     75%     max       count         mean   
Screen               ...                                            
10.10     64.000000  ...    64.0    64.0         1.0   324.000000   
10.50    164.571429  ...   192.0   256.0         7.0   894.582857   
10.95    128.000000  ...   128.0   128.0         1.0   531.000000   
11.60     70.000000  ...   128.0   128.0        16.0   358.380625   
12.00    320.000000  ...   320.0   512.0         4.0   601.472500   
12.30    457.230769  ...   512.0  1000.0        13.0  1477.185385   
12.40    149.333333  ...   224.0   256.0         6.0   796.970000   
12.50    256.000000  ...   256.0   256.0         1.0   358.990000   
13.00    362.370370  ...   512.0  1000.0        27.0  1459.942963   
13.30    397.282443  ...   512.0  1000.0       131.0  1103.023130   
13.40    858.105263  ...  1000.0  1000.0        19.0  2204.571579   
13.50    501.473684  ...   512.0  1000.0        19.0  1599.465789   
13.60    372.363636  ...   512.0   512.0        11.0  1698.092727   
13.90    512.000000  ...   512.0   512.0         2.0  1294.235000   
14.00    500.316327  ...   512.0  1000.0       392.0  1077.753138   
14.10    122.181818  ...   128.0   256.0        11.0   321.731818   
14.20    860.571429  ...  1000.0  1000.0        14.0  2762.075714   
14.40    798.666667  ...   878.0  2000.0         6.0  2343.261667   
14.50    512.000000  ...   512.0 

In [15]:
df[df["Screen"].isnull() == True]

Laptop Status   Brand  \
624   Acer Extensa 15 EX215-54 Intel Core i5-1135G7/...    New    Acer   
1430  HP ENVY x360 2-in-1 Laptop 15-ew0008np Intel C...    New      HP   
1503  Lenovo IdeaPad Gaming 3 15ACH6 AMD Ryzen 5 560...    New  Lenovo   
1548  Lenovo ThinkPad P15 Gen 2 Intel Core i7-11850H...    New  Lenovo   

         Model            CPU  RAM  Storage Storage type        GPU  Screen  \
624    Extensa  Intel Core i5    8      256          SSD        NaN     NaN   
1430      Envy  Intel Core i7   16      512          SSD   RTX 2050     NaN   
1503   IdeaPad    AMD Ryzen 5   16      512          SSD   RTX 3060     NaN   
1548  ThinkPad  Intel Core i7   16      512          SSD  RTX A2000     NaN   

     Touch  Final Price  
624     No       524.99  
1430   Yes      1863.52  
1503    No      1505.00  
1548    No      2569.00

In [18]:
df.Screen.fillna(15.60, inplace=True)

In [21]:
df[df["Screen"].isnull() == True]

Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [24]:
df.Screen.median()

15.6

In [25]:
# Q7. Sum of weights

In [23]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [26]:
df_inn = df[df.Brand == "Innjoo"]
x = df_inn[["RAM", "Storage", "Screen"]].to_numpy()


In [28]:
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [29]:
XTX = x.T.dot(x)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [30]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [31]:
XTX_inv.dot(XTX)

array([[ 1.00000000e+00, -2.75571802e-13,  6.32385368e-15],
       [ 1.02488553e-16,  1.00000000e+00,  8.14222656e-17],
       [-7.04660473e-16, -2.84062325e-14,  1.00000000e+00]])

In [32]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [37]:
w = XTX_inv.dot(x.T).dot(y)
w.sum()

91.2998806299555